#!/usr/bin/env bash
set -euo pipefail

BANK_ID="6275"
SESSION_ID=""
ROUND_ID=""
BET_AMOUNT="100"
WIN_AMOUNT="150"
RESERVE_COUNTER="1"
SETTLE_COUNTER="2"
GAME_ID="838"
GS_CONTAINER="refactor-gs-1"
PROTOCOL_CONTAINER="refactor-protocol-adapter-1"

usage() {
  cat <<USAGE
Usage: $(basename "$0") --session-id SID [options]

Options:
  --session-id SID          Required
  --bank-id ID              Default: ${BANK_ID}
  --round-id ID             Default: autogenerated hex id
  --bet-amount AMOUNT       Default: ${BET_AMOUNT}
  --win-amount AMOUNT       Default: ${WIN_AMOUNT}
  --reserve-counter N       Default: ${RESERVE_COUNTER}
  --settle-counter N        Default: ${SETTLE_COUNTER}
  --game-id ID              Default: ${GAME_ID}
  --gs-container NAME       Default: ${GS_CONTAINER}
  --protocol-container NAME Default: ${PROTOCOL_CONTAINER}
  -h, --help                Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --session-id)
      SESSION_ID="$2"; shift 2 ;;
    --bank-id)
      BANK_ID="$2"; shift 2 ;;
    --round-id)
      ROUND_ID="$2"; shift 2 ;;
    --bet-amount)
      BET_AMOUNT="$2"; shift 2 ;;
    --win-amount)
      WIN_AMOUNT="$2"; shift 2 ;;
    --reserve-counter)
      RESERVE_COUNTER="$2"; shift 2 ;;
    --settle-counter)
      SETTLE_COUNTER="$2"; shift 2 ;;
    --game-id)
      GAME_ID="$2"; shift 2 ;;
    --gs-container)
      GS_CONTAINER="$2"; shift 2 ;;
    --protocol-container)
      PROTOCOL_CONTAINER="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${SESSION_ID}" ]]; then
  echo "--session-id is required" >&2
  usage
  exit 1
fi

if [[ -z "${ROUND_ID}" ]]; then
  ROUND_ID="$(printf '%x%08x' "$(date +%s)" "$RANDOM")"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd docker
require_cmd grep
require_cmd wc
require_cmd tr

protocol_api_to_file() {
  local path="$1"
  local out_file="$2"
  docker exec "${PROTOCOL_CONTAINER}" sh -lc "wget -qO- 'http://127.0.0.1:18078${path}'" > "${out_file}"
}

count_protocol_events_from_file() {
  local file="$1"
  grep -o '"type":"PROTOCOL_REQUEST_EVALUATED"' "${file}" | wc -l | tr -d ' '
}

post_gs_internal() {
  local path="$1"
  local body="$2"
  local out_file="$3"
  local code_file="$4"
  docker exec "${GS_CONTAINER}" sh -lc "curl -sS -X POST 'http://127.0.0.1:8080/gs-internal/newgames/v1${path}' -H 'Content-Type: application/json' -d '${body}' -o '${out_file}' -w '%{http_code}'" > "${code_file}"
  docker exec "${GS_CONTAINER}" sh -lc "cat '${out_file}'" > "${out_file}.host"
}

extract_wallet_operation_id() {
  local json_file="$1"
  grep -o '"walletOperationId":"[^"]*"' "${json_file}" | head -n1 | cut -d':' -f2 | tr -d '"'
}

tmp_dir="$(mktemp -d)"
before_file="${tmp_dir}/before.json"
after_file="${tmp_dir}/after.json"
decision_file="${tmp_dir}/decision.json"
reserve_body_file="${tmp_dir}/reserve.body"
reserve_code_file="${tmp_dir}/reserve.code"
settle_body_file="${tmp_dir}/settle.body"
settle_code_file="${tmp_dir}/settle.code"
trap 'rm -rf "${tmp_dir}"' EXIT

protocol_api_to_file "/api/v1/protocol/events?limit=1000" "${before_file}"
before_count="$(count_protocol_events_from_file "${before_file}")"

protocol_api_to_file "/api/v1/protocol/routing/decision?bankId=${BANK_ID}" "${decision_file}"
if ! grep -q '"routeToProtocolAdapter":true' "${decision_file}"; then
  echo "FAIL: protocol-adapter canary route decision is not enabled for bank ${BANK_ID}" >&2
  echo "Decision payload: $(cat "${decision_file}")" >&2
  exit 2
fi

reserve_payload=$(cat <<JSON
{"sessionId":"${SESSION_ID}","roundId":"${ROUND_ID}","requestCounter":${RESERVE_COUNTER},"betAmount":${BET_AMOUNT},"gameId":${GAME_ID}}
JSON
)
post_gs_internal "/wallet/reserve" "${reserve_payload}" "/tmp/phase4-protocol-wallet-reserve.json" "${reserve_code_file}"
reserve_http_code="$(cat "${reserve_code_file}" | tr -d '\r\n')"
cp "/tmp/phase4-protocol-wallet-reserve.json.host" "${reserve_body_file}" 2>/dev/null || true

if [[ "${reserve_http_code}" != "200" ]]; then
  echo "FAIL: reserve returned HTTP ${reserve_http_code}" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 3
fi

wallet_operation_id="$(extract_wallet_operation_id "${reserve_body_file}")"
if [[ -z "${wallet_operation_id}" ]]; then
  echo "FAIL: walletOperationId missing in reserve response" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 4
fi

settle_payload=$(cat <<JSON
{"sessionId":"${SESSION_ID}","roundId":"${ROUND_ID}","walletOperationId":"${wallet_operation_id}","requestCounter":${SETTLE_COUNTER},"winAmount":${WIN_AMOUNT},"gameId":${GAME_ID}}
JSON
)
post_gs_internal "/wallet/settle" "${settle_payload}" "/tmp/phase4-protocol-wallet-settle.json" "${settle_code_file}"
settle_http_code="$(cat "${settle_code_file}" | tr -d '\r\n')"
cp "/tmp/phase4-protocol-wallet-settle.json.host" "${settle_body_file}" 2>/dev/null || true

if [[ "${settle_http_code}" != "200" ]]; then
  echo "FAIL: settle returned HTTP ${settle_http_code}" >&2
  echo "Settle body: $(cat "${settle_body_file}" 2>/dev/null || true)" >&2
  exit 5
fi

sleep 1
protocol_api_to_file "/api/v1/protocol/events?limit=1000" "${after_file}"
after_count="$(count_protocol_events_from_file "${after_file}")"

echo "Protocol wallet shadow canary summary"
echo "  bankId: ${BANK_ID}"
echo "  sessionId: ${SESSION_ID}"
echo "  roundId: ${ROUND_ID}"
echo "  reserve_http: ${reserve_http_code}"
echo "  settle_http: ${settle_http_code}"
echo "  walletOperationId: ${wallet_operation_id}"
echo "  protocol_events_before: ${before_count}"
echo "  protocol_events_after: ${after_count}"

if (( after_count <= before_count )); then
  echo "FAIL: no protocol shadow events observed after reserve/settle" >&2
  exit 6
fi

echo "PASS: protocol-adapter wallet reserve/settle shadow observed (${before_count} -> ${after_count})."
