#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/Users/alexb/Documents/Dev/Dev_new/gs-server/deploy/scripts/lib/cluster-hosts.sh
source "${SCRIPT_DIR}/lib/cluster-hosts.sh"

BANK_ID="6275"
GAME_ID="838"
MODE="real"
LANG="en"
TOKEN="test_user_6275"
TRANSPORT="host"
GS_BASE_URL="$(cluster_hosts_http_url GS_EXTERNAL_HOST GS_EXTERNAL_PORT 127.0.0.1 18081)"
GAMEPLAY_BASE_URL="$(cluster_hosts_http_url GAMEPLAY_ORCHESTRATOR_EXTERNAL_HOST GAMEPLAY_ORCHESTRATOR_EXTERNAL_PORT 127.0.0.1 18074)"
GS_CONTAINER="refactor-gs-1"
GAMEPLAY_CONTAINER="refactor-gameplay-orchestrator-1"
REQUIRE_REDIS_HIT="false"
CHECK_FINANCIAL_INTENTS="true"
ROUND_ID=""
BET_AMOUNT="100"
WIN_AMOUNT="150"
RESERVE_COUNTER="1"
SETTLE_COUNTER="2"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --bank-id ID               Default: ${BANK_ID}
  --game-id ID               Default: ${GAME_ID}
  --token TOKEN              Default: ${TOKEN}
  --mode MODE                Default: ${MODE}
  --lang LANG                Default: ${LANG}
  --transport MODE           host|docker (default: ${TRANSPORT})
  --gs-base-url URL          Default: ${GS_BASE_URL}
  --gameplay-base-url URL    Default: ${GAMEPLAY_BASE_URL}
  --gs-container NAME        Default: ${GS_CONTAINER}
  --gameplay-container NAME  Default: ${GAMEPLAY_CONTAINER}
  --require-redis-hit BOOL   true|false (default: ${REQUIRE_REDIS_HIT})
  --check-financial-intents BOOL  true|false (default: ${CHECK_FINANCIAL_INTENTS})
  --round-id ID              Optional (autogenerated if empty)
  --bet-amount AMOUNT        Default: ${BET_AMOUNT}
  --win-amount AMOUNT        Default: ${WIN_AMOUNT}
  --reserve-counter N        Default: ${RESERVE_COUNTER}
  --settle-counter N         Default: ${SETTLE_COUNTER}
  -h, --help                 Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bank-id)
      BANK_ID="$2"; shift 2 ;;
    --game-id)
      GAME_ID="$2"; shift 2 ;;
    --token)
      TOKEN="$2"; shift 2 ;;
    --mode)
      MODE="$2"; shift 2 ;;
    --lang)
      LANG="$2"; shift 2 ;;
    --transport)
      TRANSPORT="$2"; shift 2 ;;
    --gs-base-url)
      GS_BASE_URL="$2"; shift 2 ;;
    --gameplay-base-url)
      GAMEPLAY_BASE_URL="$2"; shift 2 ;;
    --gs-container)
      GS_CONTAINER="$2"; shift 2 ;;
    --gameplay-container)
      GAMEPLAY_CONTAINER="$2"; shift 2 ;;
    --require-redis-hit)
      REQUIRE_REDIS_HIT="$(echo "$2" | tr '[:upper:]' '[:lower:]')"; shift 2 ;;
    --check-financial-intents)
      CHECK_FINANCIAL_INTENTS="$(echo "$2" | tr '[:upper:]' '[:lower:]')"; shift 2 ;;
    --round-id)
      ROUND_ID="$2"; shift 2 ;;
    --bet-amount)
      BET_AMOUNT="$2"; shift 2 ;;
    --win-amount)
      WIN_AMOUNT="$2"; shift 2 ;;
    --reserve-counter)
      RESERVE_COUNTER="$2"; shift 2 ;;
    --settle-counter)
      SETTLE_COUNTER="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${ROUND_ID}" ]]; then
  ROUND_ID="$(printf '%x%08x' "$(date +%s)" "$RANDOM")"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd curl
require_cmd grep
require_cmd wc
require_cmd tr
require_cmd mktemp

if [[ "${TRANSPORT}" != "host" && "${TRANSPORT}" != "docker" ]]; then
  echo "Invalid --transport: ${TRANSPORT}" >&2
  exit 1
fi

if [[ "${TRANSPORT}" == "docker" ]]; then
  require_cmd docker
fi

api_get_to_file() {
  local path="$1"
  local out_file="$2"
  if [[ "${TRANSPORT}" == "host" ]]; then
    curl -fsS "${GAMEPLAY_BASE_URL}${path}" > "${out_file}"
  else
    docker exec "${GAMEPLAY_CONTAINER}" sh -lc "curl -fsS 'http://127.0.0.1:18074${path}'" > "${out_file}"
  fi
}

api_put_json_to_file() {
  local path="$1"
  local payload="$2"
  local out_file="$3"
  if [[ "${TRANSPORT}" == "host" ]]; then
    curl -fsS -X PUT \
      -H "Content-Type: application/json" \
      --data "${payload}" \
      "${GAMEPLAY_BASE_URL}${path}" > "${out_file}"
  else
    docker exec "${GAMEPLAY_CONTAINER}" sh -lc "curl -fsS -X PUT -H 'Content-Type: application/json' --data '${payload}' 'http://127.0.0.1:18074${path}'" > "${out_file}"
  fi
}

gs_launch_http_with_body() {
  local headers_file="$1"
  local body_file="$2"
  local code_file="$3"
  local url="${GS_BASE_URL}/cwstartgamev2.do?bankId=${BANK_ID}&gameId=${GAME_ID}&mode=${MODE}&token=${TOKEN}&lang=${LANG}"
  if [[ "${TRANSPORT}" == "host" ]]; then
    curl -sS -D "${headers_file}" -o "${body_file}" -w '%{http_code}' "${url}" > "${code_file}"
  else
    local docker_url="http://127.0.0.1:8080/cwstartgamev2.do?bankId=${BANK_ID}&gameId=${GAME_ID}&mode=${MODE}&token=${TOKEN}&lang=${LANG}"
    docker exec "${GS_CONTAINER}" sh -lc "curl -sS -D /tmp/phase5-gameplay-launch.headers -o /tmp/phase5-gameplay-launch.body -w '%{http_code}' '${docker_url}'" > "${code_file}"
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-gameplay-launch.headers" > "${headers_file}" || true
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-gameplay-launch.body" > "${body_file}" || true
  fi
}

post_gs_internal() {
  local path="$1"
  local body="$2"
  local out_file="$3"
  local code_file="$4"
  if [[ "${TRANSPORT}" == "host" ]]; then
    curl -sS -X POST "${GS_BASE_URL}/gs-internal/newgames/v1${path}" \
      -H 'Content-Type: application/json' \
      -d "${body}" \
      -o "${out_file}" \
      -w '%{http_code}' > "${code_file}"
  else
    docker exec "${GS_CONTAINER}" sh -lc "curl -sS -X POST 'http://127.0.0.1:8080/gs-internal/newgames/v1${path}' -H 'Content-Type: application/json' -d '${body}' -o '/tmp/phase5-gameplay-wallet.out' -w '%{http_code}'" > "${code_file}"
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-gameplay-wallet.out" > "${out_file}" || true
  fi
}

count_intents_from_file() {
  local file="$1"
  local intent_type="$2"
  grep -o "\"type\":\"${intent_type}\"" "${file}" | wc -l | tr -d ' '
}

extract_string_field() {
  local key="$1"
  local file="$2"
  grep -o "\"${key}\":\"[^\"]*\"" "${file}" | head -n1 | cut -d'"' -f4
}

extract_bool_field() {
  local key="$1"
  local file="$2"
  grep -o "\"${key}\":[^,}]*" "${file}" | head -n1 | cut -d':' -f2 | tr -d '[:space:]'
}

extract_sid_from_file() {
  local file="$1"
  grep -Eo 'SID=[^&"[:space:]]+' "${file}" | head -n1 | cut -d'=' -f2 || true
}

extract_wallet_operation_id() {
  local json_file="$1"
  grep -o '"walletOperationId":"[^"]*"' "${json_file}" | head -n1 | cut -d':' -f2 | tr -d '"'
}

tmp_dir="$(mktemp -d)"
launch_before_file="${tmp_dir}/launch.before.json"
launch_after_file="${tmp_dir}/launch.after.json"
wager_before_file="${tmp_dir}/wager.before.json"
wager_after_file="${tmp_dir}/wager.after.json"
settle_before_file="${tmp_dir}/settle.before.json"
settle_after_file="${tmp_dir}/settle.after.json"
decision_file="${tmp_dir}/decision.json"
health_file="${tmp_dir}/health.json"
launch_headers_file="${tmp_dir}/launch.headers"
launch_body_file="${tmp_dir}/launch.body"
launch_code_file="${tmp_dir}/launch.code"
state_put_file="${tmp_dir}/state_put.json"
state_get_file="${tmp_dir}/state_get.json"
reserve_body_file="${tmp_dir}/reserve.body"
reserve_code_file="${tmp_dir}/reserve.code"
settle_body_file="${tmp_dir}/settle.body"
settle_code_file="${tmp_dir}/settle.code"
trap 'rm -rf "${tmp_dir}"' EXIT

api_get_to_file "/health" "${health_file}"
configured_backend="$(extract_string_field "configuredBackend" "${health_file}")"

api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=launch" "${launch_before_file}"
launch_before="$(count_intents_from_file "${launch_before_file}" "launch")"

api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=wager" "${wager_before_file}"
wager_before="$(count_intents_from_file "${wager_before_file}" "wager")"

api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=settle" "${settle_before_file}"
settle_before="$(count_intents_from_file "${settle_before_file}" "settle")"

api_get_to_file "/api/v1/gameplay/routing/decision?bankId=${BANK_ID}&isMultiplayer=false" "${decision_file}"
if ! grep -q '"routeToGameplayService":true' "${decision_file}"; then
  echo "FAIL: gameplay canary route decision is not enabled for bank ${BANK_ID}" >&2
  echo "Decision payload: $(cat "${decision_file}")" >&2
  exit 2
fi

gs_launch_http_with_body "${launch_headers_file}" "${launch_body_file}" "${launch_code_file}"
launch_http="$(cat "${launch_code_file}" | tr -d '\r\n')"
session_id="$(extract_sid_from_file "${launch_headers_file}")"
if [[ -z "${session_id}" ]]; then
  session_id="$(extract_sid_from_file "${launch_body_file}")"
fi

sleep 1
api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=launch" "${launch_after_file}"
launch_after="$(count_intents_from_file "${launch_after_file}" "launch")"

state_key="canary-${BANK_ID}-$(date +%s)"
state_payload="{\"seed\":\"bank-${BANK_ID}-seed\",\"state\":{\"round\":1,\"step\":\"wager\"},\"context\":{\"bankId\":\"${BANK_ID}\",\"gameId\":\"${GAME_ID}\"},\"ttlSeconds\":120}"
api_put_json_to_file "/api/v1/gameplay/state-blobs/${state_key}" "${state_payload}" "${state_put_file}"
api_get_to_file "/api/v1/gameplay/state-blobs/${state_key}" "${state_get_file}"

cache_backend="$(extract_string_field "cacheBackend" "${state_get_file}")"
degraded_from_redis="$(extract_bool_field "degradedFromRedis" "${state_get_file}")"
fingerprint="$(extract_string_field "fingerprint" "${state_get_file}")"

financial_status="SKIPPED"
wallet_operation_id=""
reserve_http="n/a"
settle_http="n/a"
wager_after="${wager_before}"
settle_after="${settle_before}"

if [[ "${CHECK_FINANCIAL_INTENTS}" == "true" ]]; then
  if [[ -z "${session_id}" ]]; then
    echo "FAIL: cannot test financial intents because sessionId was not found in launch response" >&2
    exit 5
  fi

  reserve_payload="{\"sessionId\":\"${session_id}\",\"roundId\":\"${ROUND_ID}\",\"requestCounter\":${RESERVE_COUNTER},\"betAmount\":${BET_AMOUNT},\"gameId\":${GAME_ID}}"
  post_gs_internal "/wallet/reserve" "${reserve_payload}" "${reserve_body_file}" "${reserve_code_file}"
  reserve_http="$(cat "${reserve_code_file}" | tr -d '\r\n')"
  if [[ "${reserve_http}" != "200" ]]; then
    echo "FAIL: reserve returned HTTP ${reserve_http}" >&2
    echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
    exit 6
  fi

  wallet_operation_id="$(extract_wallet_operation_id "${reserve_body_file}")"
  if [[ -z "${wallet_operation_id}" ]]; then
    echo "FAIL: walletOperationId missing in reserve response" >&2
    echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
    exit 7
  fi

  settle_payload="{\"sessionId\":\"${session_id}\",\"roundId\":\"${ROUND_ID}\",\"walletOperationId\":\"${wallet_operation_id}\",\"requestCounter\":${SETTLE_COUNTER},\"winAmount\":${WIN_AMOUNT},\"gameId\":${GAME_ID}}"
  post_gs_internal "/wallet/settle" "${settle_payload}" "${settle_body_file}" "${settle_code_file}"
  settle_http="$(cat "${settle_code_file}" | tr -d '\r\n')"
  if [[ "${settle_http}" != "200" ]]; then
    echo "FAIL: settle returned HTTP ${settle_http}" >&2
    echo "Settle body: $(cat "${settle_body_file}" 2>/dev/null || true)" >&2
    exit 8
  fi

  sleep 1
  api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=wager" "${wager_after_file}"
  api_get_to_file "/api/v1/gameplay/intents?bankId=${BANK_ID}&type=settle" "${settle_after_file}"
  wager_after="$(count_intents_from_file "${wager_after_file}" "wager")"
  settle_after="$(count_intents_from_file "${settle_after_file}" "settle")"
  financial_status="ENABLED"
fi

echo "Gameplay canary probe summary"
echo "  transport: ${TRANSPORT}"
echo "  bankId: ${BANK_ID}"
echo "  decision: routeToGameplayService=true"
echo "  sessionId: ${session_id:-missing}"
echo "  launch_http: ${launch_http}"
echo "  launch_intents_before: ${launch_before}"
echo "  launch_intents_after: ${launch_after}"
echo "  financial_check: ${financial_status}"
echo "  reserve_http: ${reserve_http}"
echo "  settle_http: ${settle_http}"
echo "  walletOperationId: ${wallet_operation_id:-n/a}"
echo "  wager_intents_before: ${wager_before}"
echo "  wager_intents_after: ${wager_after}"
echo "  settle_intents_before: ${settle_before}"
echo "  settle_intents_after: ${settle_after}"
echo "  state_cache_configured_backend: ${configured_backend:-unknown}"
echo "  state_blob_cache_backend: ${cache_backend:-unknown}"
echo "  state_blob_degraded_from_redis: ${degraded_from_redis:-unknown}"
echo "  state_blob_fingerprint: ${fingerprint:-missing}"

if [[ "${launch_http}" != "200" && "${launch_http}" != "302" ]]; then
  echo "FAIL: launch returned unexpected HTTP ${launch_http}" >&2
  exit 3
fi

if (( launch_after <= launch_before )); then
  echo "FAIL: no new launch intent observed in gameplay-orchestrator shadow path" >&2
  exit 4
fi

if [[ -z "${fingerprint}" ]]; then
  echo "FAIL: state-blob fingerprint is missing" >&2
  exit 9
fi

if [[ "${CHECK_FINANCIAL_INTENTS}" == "true" ]]; then
  if (( wager_after <= wager_before )); then
    echo "FAIL: no new wager intent observed after reserve flow" >&2
    exit 10
  fi
  if (( settle_after <= settle_before )); then
    echo "FAIL: no new settle intent observed after settle flow" >&2
    exit 11
  fi
fi

if [[ "${REQUIRE_REDIS_HIT}" == "true" && "${cache_backend}" != "redis" ]]; then
  echo "FAIL: expected Redis state-blob hit but backend was '${cache_backend:-unknown}'" >&2
  exit 12
fi

echo "PASS: gameplay-orchestrator launch, financial, and state-blob shadow flows verified."
