#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/Users/alexb/Documents/Dev/Dev_new"
OUT_FILE="${ROOT_DIR}/docs/phase0/parity-fixture.env"

BANK_ID=""
GAME_ID=""
TOKEN=""
EXTERNAL_BANK_ID=""
EXT_BONUS_ID=""
BONUS_PASS_KEY=""

USER_ID=""
CURRENCY="USD"
WAGER_AMOUNT="0.1"
SETTLE_AMOUNT="0.1"

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") --bank-id ID --game-id ID --token TOKEN --external-bank-id ID --ext-bonus-id ID --bonus-pass-key KEY [options]

Required:
  --bank-id VALUE
  --game-id VALUE
  --token VALUE
  --external-bank-id VALUE
  --ext-bonus-id VALUE
  --bonus-pass-key VALUE

Optional:
  --user-id VALUE
  --currency VALUE            Default: USD
  --wager-amount VALUE        Default: 0.1
  --settle-amount VALUE       Default: 0.1
  --out-file PATH             Default: /Users/alexb/Documents/Dev/Dev_new/docs/phase0/parity-fixture.env
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bank-id) BANK_ID="$2"; shift 2 ;;
    --game-id) GAME_ID="$2"; shift 2 ;;
    --token) TOKEN="$2"; shift 2 ;;
    --external-bank-id) EXTERNAL_BANK_ID="$2"; shift 2 ;;
    --ext-bonus-id) EXT_BONUS_ID="$2"; shift 2 ;;
    --bonus-pass-key) BONUS_PASS_KEY="$2"; shift 2 ;;
    --user-id) USER_ID="$2"; shift 2 ;;
    --currency) CURRENCY="$2"; shift 2 ;;
    --wager-amount) WAGER_AMOUNT="$2"; shift 2 ;;
    --settle-amount) SETTLE_AMOUNT="$2"; shift 2 ;;
    --out-file) OUT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

for required in BANK_ID GAME_ID TOKEN EXTERNAL_BANK_ID EXT_BONUS_ID BONUS_PASS_KEY; do
  if [[ -z "${!required}" ]]; then
    echo "Missing required option for ${required}" >&2
    usage
    exit 1
  fi
done

HASH_OUTPUT="$("${ROOT_DIR}/gs-server/deploy/scripts/phase0-bonus-hash-helper.sh" \
  --mode check \
  --ext-bonus-id "${EXT_BONUS_ID}" \
  --external-bank-id "${EXTERNAL_BANK_ID}" \
  --bonus-pass-key "${BONUS_PASS_KEY}")"

BONUS_HASH="$(echo "${HASH_OUTPUT}" | awk -F= '/^HASH=/{print $2}')"
if [[ -z "${BONUS_HASH}" ]]; then
  echo "Failed to compute BONUS_HASH" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"
cat > "${OUT_FILE}" <<EOF
# Generated by gs-server/deploy/scripts/phase0-fixture-bootstrap.sh at $(date -u +"%Y-%m-%d %H:%M:%S UTC")
BANK_ID=${BANK_ID}
GAME_ID=${GAME_ID}
TOKEN=${TOKEN}
LANG_CODE=en
GAME_MODE=real

USER_ID=${USER_ID}
CURRENCY=${CURRENCY}
WAGER_AMOUNT=${WAGER_AMOUNT}
SETTLE_AMOUNT=${SETTLE_AMOUNT}
EXT_BONUS_ID=${EXT_BONUS_ID}
BONUS_HASH=${BONUS_HASH}

# Deterministic negative-case probes
NEG_BANK_ID=999999
NEG_GAME_ID=${GAME_ID}
NEG_TOKEN=invalid_token
EOF

echo "Fixture file created: ${OUT_FILE}"
