#!/usr/bin/env bash
set -euo pipefail

MANIFEST_FILE=""
TEMPLATE_FILE="/Users/alexb/Documents/Dev/Dev_new/docs/phase7/cassandra/rehearsal-report-template.md"
OUTPUT_DIR="/Users/alexb/Documents/Dev/Dev_new/docs/phase7/cassandra"
TS="$(date -u '+%Y%m%d-%H%M%S')"
OUT_FILE="${OUTPUT_DIR}/phase7-cassandra-rehearsal-report-${TS}.md"

usage() {
  cat <<USAGE
Usage: $(basename "$0") --manifest FILE [options]

Required:
  --manifest FILE   Manifest generated by phase7-cassandra-evidence-pack.sh

Options:
  --template FILE   Report template (default: ${TEMPLATE_FILE})
  --output-dir DIR  Output directory (default: ${OUTPUT_DIR})
  -h, --help        Show help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)
      MANIFEST_FILE="$2"; shift 2 ;;
    --template)
      TEMPLATE_FILE="$2"; shift 2 ;;
    --output-dir)
      OUTPUT_DIR="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "$MANIFEST_FILE" || ! -f "$MANIFEST_FILE" ]]; then
  echo "manifest file is required and must exist" >&2
  exit 1
fi
if [[ ! -f "$TEMPLATE_FILE" ]]; then
  echo "template file not found: ${TEMPLATE_FILE}" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
cp "$TEMPLATE_FILE" "$OUT_FILE"

extract_output() {
  local key="$1"
  awk -F':OUTPUT:' -v k="$key" '$1 ~ ("^" k "$") {print $2}' "$MANIFEST_FILE" | tail -n 1
}

prefill_line() {
  local label="$1"
  local value="$2"
  perl -0777 -i -pe "s#${label}:\n#${label}: ${value}\n#g" "$OUT_FILE"
}

schema_source="$(extract_output schema_export)"
counts_source="$(extract_output table_counts)"
preflight_source="$(extract_output preflight)"
query_smoke_source="$(extract_output query_smoke)"

prefill_line "Date \(UTC\)" "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
prefill_line "Environment" "refactor"
prefill_line "Source cluster" "legacy/refactor-c1-1 (set actual)"
prefill_line "Target cluster" "target-candidate (set actual)"
prefill_line "Schema source" "${schema_source}"
prefill_line "Count report source" "${counts_source}"
prefill_line "Runtime parity report" "${query_smoke_source}"
prefill_line "Performance summary" "${preflight_source}"

echo "rehearsal_report=${OUT_FILE}"
