#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/Users/alexb/Documents/Dev/Dev_new/gs-server/deploy/scripts/lib/cluster-hosts.sh
source "${SCRIPT_DIR}/lib/cluster-hosts.sh"

BANK_ID="6275"
SESSION_ID=""
ROUND_ID=""
BET_AMOUNT="100"
WIN_AMOUNT="150"
RESERVE_COUNTER="1"
SETTLE_COUNTER="2"
GAME_ID="838"
MODE="real"
LANG="en"
TOKEN="test_user_6275"
SUB_CASINO_ID=""
TRANSPORT="host"
GS_BASE_URL="$(cluster_hosts_http_url GS_EXTERNAL_HOST GS_EXTERNAL_PORT 127.0.0.1 18081)"
WALLET_BASE_URL="$(cluster_hosts_http_url WALLET_ADAPTER_EXTERNAL_HOST WALLET_ADAPTER_EXTERNAL_PORT 127.0.0.1 18075)"
GS_CONTAINER="refactor-gs-1"
WALLET_CONTAINER="refactor-wallet-adapter-1"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --session-id SID        Optional (auto-detected if omitted)
  --bank-id ID            Default: ${BANK_ID}
  --token TOKEN           Default: ${TOKEN}
  --sub-casino-id ID      Optional (appended to startgame launch URL)
  --mode MODE             Default: ${MODE}
  --lang LANG             Default: ${LANG}
  --round-id ID           Default: autogenerated hex id
  --bet-amount AMOUNT     Default: ${BET_AMOUNT}
  --win-amount AMOUNT     Default: ${WIN_AMOUNT}
  --reserve-counter N     Default: ${RESERVE_COUNTER}
  --settle-counter N      Default: ${SETTLE_COUNTER}
  --game-id ID            Default: ${GAME_ID}
  --transport MODE        host|docker (default: ${TRANSPORT})
  --gs-base-url URL       Default: ${GS_BASE_URL}
  --wallet-base-url URL   Default: ${WALLET_BASE_URL}
  --gs-container NAME     Default: ${GS_CONTAINER}
  --wallet-container NAME Default: ${WALLET_CONTAINER}
  -h, --help              Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --session-id)
      SESSION_ID="$2"; shift 2 ;;
    --bank-id)
      BANK_ID="$2"; shift 2 ;;
    --token)
      TOKEN="$2"; shift 2 ;;
    --sub-casino-id)
      SUB_CASINO_ID="$2"; shift 2 ;;
    --mode)
      MODE="$2"; shift 2 ;;
    --lang)
      LANG="$2"; shift 2 ;;
    --round-id)
      ROUND_ID="$2"; shift 2 ;;
    --bet-amount)
      BET_AMOUNT="$2"; shift 2 ;;
    --win-amount)
      WIN_AMOUNT="$2"; shift 2 ;;
    --reserve-counter)
      RESERVE_COUNTER="$2"; shift 2 ;;
    --settle-counter)
      SETTLE_COUNTER="$2"; shift 2 ;;
    --game-id)
      GAME_ID="$2"; shift 2 ;;
    --transport)
      TRANSPORT="$2"; shift 2 ;;
    --gs-base-url)
      GS_BASE_URL="$2"; shift 2 ;;
    --wallet-base-url)
      WALLET_BASE_URL="$2"; shift 2 ;;
    --gs-container)
      GS_CONTAINER="$2"; shift 2 ;;
    --wallet-container)
      WALLET_CONTAINER="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${ROUND_ID}" ]]; then
  ROUND_ID="$(printf '%x%08x' "$(date +%s)" "$RANDOM")"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd grep
require_cmd wc
require_cmd tr
require_cmd curl

if [[ "${TRANSPORT}" != "host" && "${TRANSPORT}" != "docker" ]]; then
  echo "Invalid --transport: ${TRANSPORT}" >&2
  exit 1
fi

if [[ "${TRANSPORT}" == "docker" ]]; then
  require_cmd docker
fi

extract_sid_from_file() {
  local file="$1"
  if [[ ! -f "${file}" ]]; then
    echo ""
    return 0
  fi
  local sid
  sid="$(grep -Eo 'SID=[^&"[:space:]]+' "${file}" | head -n1 | cut -d'=' -f2 || true)"
  if [[ -n "${sid}" ]]; then
    echo "${sid}"
    return 0
  fi
  echo ""
}

resolve_session_id() {
  local out_headers="$1"
  local out_body="$2"
  local launch_url
  local launch_query="bankId=${BANK_ID}&gameId=${GAME_ID}&mode=${MODE}&token=${TOKEN}&lang=${LANG}"
  if [[ -n "${SUB_CASINO_ID}" ]]; then
    launch_query="${launch_query}&subCasinoId=${SUB_CASINO_ID}"
  fi
  if [[ "${TRANSPORT}" == "docker" ]]; then
    launch_url="http://127.0.0.1:8080/cwstartgamev2.do?${launch_query}"
    if ! docker exec "${GS_CONTAINER}" sh -lc "curl -sS -D /tmp/phase5-wallet-launch.headers -o /tmp/phase5-wallet-launch.body '${launch_url}' >/dev/null"; then
      : > "${out_headers}"
      : > "${out_body}"
      echo ""
      return 0
    fi
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-wallet-launch.headers" > "${out_headers}" || true
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-wallet-launch.body" > "${out_body}" || true
  else
    launch_url="${GS_BASE_URL}/cwstartgamev2.do?${launch_query}"
    if ! curl -sS -D "${out_headers}" -o "${out_body}" "${launch_url}" >/dev/null; then
      : > "${out_headers}"
      : > "${out_body}"
      echo ""
      return 0
    fi
  fi

  local sid
  sid="$(extract_sid_from_file "${out_headers}")"
  if [[ -z "${sid}" ]]; then
    sid="$(extract_sid_from_file "${out_body}")"
  fi
  echo "${sid}"
}

wallet_api_to_file() {
  local path="$1"
  local out_file="$2"
  if [[ "${TRANSPORT}" == "docker" ]]; then
    docker exec "${WALLET_CONTAINER}" sh -lc "curl -fsS 'http://127.0.0.1:18075${path}'" > "${out_file}"
  else
    curl -fsS "${WALLET_BASE_URL}${path}" > "${out_file}"
  fi
}

count_wallet_ops_from_file() {
  local file="$1"
  local op_type="$2"
  (grep -o "\"type\":\"${op_type}\"" "${file}" || true) | wc -l | tr -d ' '
}

post_gs_internal() {
  local path="$1"
  local body="$2"
  local out_file="$3"
  local code_file="$4"
  if [[ "${TRANSPORT}" == "docker" ]]; then
    docker exec "${GS_CONTAINER}" sh -lc "curl -sS -X POST 'http://127.0.0.1:8080/gs-internal/newgames/v1${path}' -H 'Content-Type: application/json' -d '${body}' -o '/tmp/phase5-wallet.out' -w '%{http_code}'" > "${code_file}"
    docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase5-wallet.out" > "${out_file}" || true
  else
    curl -sS -X POST "${GS_BASE_URL}/gs-internal/newgames/v1${path}" \
      -H 'Content-Type: application/json' \
      -d "${body}" \
      -o "${out_file}" \
      -w '%{http_code}' > "${code_file}"
  fi
}

extract_wallet_operation_id() {
  local json_file="$1"
  grep -o '"walletOperationId":"[^"]*"' "${json_file}" | head -n1 | cut -d':' -f2 | tr -d '"'
}

tmp_dir="$(mktemp -d)"
before_reserve_file="${tmp_dir}/before.reserve.json"
before_settle_file="${tmp_dir}/before.settle.json"
after_reserve_file="${tmp_dir}/after.reserve.json"
after_settle_file="${tmp_dir}/after.settle.json"
decision_file="${tmp_dir}/decision.json"
launch_headers_file="${tmp_dir}/launch.headers"
launch_body_file="${tmp_dir}/launch.body"
reserve_body_file="${tmp_dir}/reserve.body"
reserve_code_file="${tmp_dir}/reserve.code"
settle_body_file="${tmp_dir}/settle.body"
settle_code_file="${tmp_dir}/settle.code"
trap 'rm -rf "${tmp_dir}"' EXIT

if [[ -z "${SESSION_ID}" ]]; then
  SESSION_ID="$(resolve_session_id "${launch_headers_file}" "${launch_body_file}")"
fi
if [[ -z "${SESSION_ID}" ]]; then
  echo "FAIL: could not auto-resolve sessionId from startgame launch" >&2
  echo "Launch headers:" >&2
  cat "${launch_headers_file}" >&2 || true
  echo "Launch body snippet:" >&2
  sed -n '1,40p' "${launch_body_file}" >&2 || true
  exit 1
fi

wallet_api_to_file "/api/v1/wallet/operations?bankId=${BANK_ID}&type=reserve" "${before_reserve_file}"
wallet_api_to_file "/api/v1/wallet/operations?bankId=${BANK_ID}&type=settle" "${before_settle_file}"
before_reserve_count="$(count_wallet_ops_from_file "${before_reserve_file}" "reserve")"
before_settle_count="$(count_wallet_ops_from_file "${before_settle_file}" "settle")"

wallet_api_to_file "/api/v1/wallet/routing/decision?bankId=${BANK_ID}" "${decision_file}"
if ! grep -q '"routeToWalletAdapter":true' "${decision_file}"; then
  echo "FAIL: wallet-adapter canary route decision is not enabled for bank ${BANK_ID}" >&2
  echo "Decision payload: $(cat "${decision_file}")" >&2
  exit 2
fi

reserve_payload="{\"sessionId\":\"${SESSION_ID}\",\"roundId\":\"${ROUND_ID}\",\"requestCounter\":${RESERVE_COUNTER},\"betAmount\":${BET_AMOUNT},\"gameId\":${GAME_ID}}"
post_gs_internal "/wallet/reserve" "${reserve_payload}" "${reserve_body_file}" "${reserve_code_file}"
reserve_http_code="$(cat "${reserve_code_file}" | tr -d '\r\n')"

if [[ "${reserve_http_code}" != "200" ]]; then
  echo "FAIL: reserve returned HTTP ${reserve_http_code}" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 3
fi

wallet_operation_id="$(extract_wallet_operation_id "${reserve_body_file}")"
if [[ -z "${wallet_operation_id}" ]]; then
  echo "FAIL: walletOperationId missing in reserve response" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 4
fi

settle_payload="{\"sessionId\":\"${SESSION_ID}\",\"roundId\":\"${ROUND_ID}\",\"walletOperationId\":\"${wallet_operation_id}\",\"requestCounter\":${SETTLE_COUNTER},\"winAmount\":${WIN_AMOUNT},\"gameId\":${GAME_ID}}"
post_gs_internal "/wallet/settle" "${settle_payload}" "${settle_body_file}" "${settle_code_file}"
settle_http_code="$(cat "${settle_code_file}" | tr -d '\r\n')"

if [[ "${settle_http_code}" != "200" ]]; then
  echo "FAIL: settle returned HTTP ${settle_http_code}" >&2
  echo "Settle body: $(cat "${settle_body_file}" 2>/dev/null || true)" >&2
  exit 5
fi

sleep 1
wallet_api_to_file "/api/v1/wallet/operations?bankId=${BANK_ID}&type=reserve" "${after_reserve_file}"
wallet_api_to_file "/api/v1/wallet/operations?bankId=${BANK_ID}&type=settle" "${after_settle_file}"
after_reserve_count="$(count_wallet_ops_from_file "${after_reserve_file}" "reserve")"
after_settle_count="$(count_wallet_ops_from_file "${after_settle_file}" "settle")"

echo "Wallet-adapter shadow canary summary"
echo "  bankId: ${BANK_ID}"
echo "  sessionId: ${SESSION_ID}"
echo "  roundId: ${ROUND_ID}"
echo "  reserve_http: ${reserve_http_code}"
echo "  settle_http: ${settle_http_code}"
echo "  walletOperationId: ${wallet_operation_id}"
echo "  reserve_ops_before: ${before_reserve_count}"
echo "  reserve_ops_after: ${after_reserve_count}"
echo "  settle_ops_before: ${before_settle_count}"
echo "  settle_ops_after: ${after_settle_count}"

if (( after_reserve_count <= before_reserve_count )); then
  echo "FAIL: no new reserve operation observed in wallet-adapter" >&2
  exit 6
fi

if (( after_settle_count <= before_settle_count )); then
  echo "FAIL: no new settle operation observed in wallet-adapter" >&2
  exit 7
fi

echo "PASS: wallet-adapter reserve/settle shadow observed."
