#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

ROOT_DIR="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
OUT_FILE="${ROOT_DIR}/docs/phase0/parity-fixture.env"

BANK_ID=""
GAME_ID=""
TOKEN=""
EXTERNAL_BANK_ID=""
EXT_BONUS_ID=""
BONUS_PASS_KEY=""

USER_ID=""
CURRENCY="USD"
WAGER_AMOUNT="0.1"
SETTLE_AMOUNT="0.1"

BSAWARD_AMOUNT="10000"
BSAWARD_GAMES="all"
BSAWARD_GAME_IDS=""
BSAWARD_EXP_DATE="$(date -u -v+30d +%d.%m.%Y 2>/dev/null || date -u -d '+30 day' +%d.%m.%Y 2>/dev/null || echo '31.12.2099')"
BSAWARD_TYPE="Deposit"
BSAWARD_MULTIPLIER="2"

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") --bank-id ID --game-id ID --token TOKEN --external-bank-id ID --ext-bonus-id ID --bonus-pass-key KEY [options]

Required:
  --bank-id VALUE
  --game-id VALUE
  --token VALUE
  --external-bank-id VALUE
  --ext-bonus-id VALUE
  --bonus-pass-key VALUE

Optional:
  --user-id VALUE
  --currency VALUE            Default: USD
  --wager-amount VALUE        Default: 0.1
  --settle-amount VALUE       Default: 0.1
  --bsaward-amount VALUE      Default: 10000
  --bsaward-games VALUE       Default: all
  --bsaward-game-ids VALUE    Default: game-id value
  --bsaward-exp-date DD.MM.YYYY  Default: +30 days UTC
  --bsaward-type VALUE        Default: Deposit
  --bsaward-multiplier VALUE  Default: 2
  --out-file PATH             Default: ${REPO_ROOT}/docs/phase0/parity-fixture.env
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bank-id) BANK_ID="$2"; shift 2 ;;
    --game-id) GAME_ID="$2"; shift 2 ;;
    --token) TOKEN="$2"; shift 2 ;;
    --external-bank-id) EXTERNAL_BANK_ID="$2"; shift 2 ;;
    --ext-bonus-id) EXT_BONUS_ID="$2"; shift 2 ;;
    --bonus-pass-key) BONUS_PASS_KEY="$2"; shift 2 ;;
    --user-id) USER_ID="$2"; shift 2 ;;
    --currency) CURRENCY="$2"; shift 2 ;;
    --wager-amount) WAGER_AMOUNT="$2"; shift 2 ;;
    --settle-amount) SETTLE_AMOUNT="$2"; shift 2 ;;
    --bsaward-amount) BSAWARD_AMOUNT="$2"; shift 2 ;;
    --bsaward-games) BSAWARD_GAMES="$2"; shift 2 ;;
    --bsaward-game-ids) BSAWARD_GAME_IDS="$2"; shift 2 ;;
    --bsaward-exp-date) BSAWARD_EXP_DATE="$2"; shift 2 ;;
    --bsaward-type) BSAWARD_TYPE="$2"; shift 2 ;;
    --bsaward-multiplier) BSAWARD_MULTIPLIER="$2"; shift 2 ;;
    --out-file) OUT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

for required in BANK_ID GAME_ID TOKEN EXTERNAL_BANK_ID EXT_BONUS_ID BONUS_PASS_KEY; do
  if [[ -z "${!required}" ]]; then
    echo "Missing required option for ${required}" >&2
    usage
    exit 1
  fi
done

if [[ -z "${BSAWARD_GAME_IDS}" ]]; then
  BSAWARD_GAME_IDS="${GAME_ID}"
fi
if [[ -z "${USER_ID}" ]]; then
  USER_ID="${TOKEN}"
fi

BSCHECK_HASH_OUTPUT="$("${ROOT_DIR}/gs-server/deploy/scripts/phase0-bonus-hash-helper.sh" \
  --mode check \
  --ext-bonus-id "${EXT_BONUS_ID}" \
  --external-bank-id "${EXTERNAL_BANK_ID}" \
  --bonus-pass-key "${BONUS_PASS_KEY}")"

BSCHECK_HASH="$(echo "${BSCHECK_HASH_OUTPUT}" | awk -F= '/^HASH=/{print $2}')"
if [[ -z "${BSCHECK_HASH}" ]]; then
  echo "Failed to compute BSCHECK_HASH" >&2
  exit 1
fi

BSAWARD_HASH_OUTPUT="$("${ROOT_DIR}/gs-server/deploy/scripts/phase0-bonus-hash-helper.sh" \
  --mode award \
  --user-id "${USER_ID}" \
  --external-bank-id "${EXTERNAL_BANK_ID}" \
  --type "${BSAWARD_TYPE}" \
  --amount "${BSAWARD_AMOUNT}" \
  --multiplier "${BSAWARD_MULTIPLIER}" \
  --games "${BSAWARD_GAMES}" \
  --game-ids "${BSAWARD_GAME_IDS}" \
  --exp-date "${BSAWARD_EXP_DATE}" \
  --ext-bonus-id "${EXT_BONUS_ID}" \
  --bonus-pass-key "${BONUS_PASS_KEY}")"

BSAWARD_HASH="$(echo "${BSAWARD_HASH_OUTPUT}" | awk -F= '/^HASH=/{print $2}')"
if [[ -z "${BSAWARD_HASH}" ]]; then
  echo "Failed to compute BSAWARD_HASH" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"
cat > "${OUT_FILE}" <<EOF
# Generated by gs-server/deploy/scripts/phase0-fixture-bootstrap.sh at $(date -u +"%Y-%m-%d %H:%M:%S UTC")
BANK_ID=${BANK_ID}
GAME_ID=${GAME_ID}
TOKEN=${TOKEN}
LANG_CODE=en
GAME_MODE=real

USER_ID=${USER_ID}
CURRENCY=${CURRENCY}
WAGER_AMOUNT=${WAGER_AMOUNT}
SETTLE_AMOUNT=${SETTLE_AMOUNT}
EXT_BONUS_ID=${EXT_BONUS_ID}

# Bonus flow fixtures
BSCHECK_HASH=${BSCHECK_HASH}
BSAWARD_HASH=${BSAWARD_HASH}
BSAWARD_AMOUNT=${BSAWARD_AMOUNT}
BSAWARD_GAMES=${BSAWARD_GAMES}
BSAWARD_GAME_IDS=${BSAWARD_GAME_IDS}
BSAWARD_EXP_DATE=${BSAWARD_EXP_DATE}
BSAWARD_TYPE=${BSAWARD_TYPE}
BSAWARD_MULTIPLIER=${BSAWARD_MULTIPLIER}

# Backward-compat alias
BONUS_HASH=${BSCHECK_HASH}

# Deterministic negative-case probes
NEG_BANK_ID=999999
NEG_GAME_ID=${GAME_ID}
NEG_TOKEN=invalid_token
EOF

echo "Fixture file created: ${OUT_FILE}"
