#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/Users/alexb/Documents/Dev/Dev_new/gs-server/deploy/scripts/lib/cluster-hosts.sh
source "${SCRIPT_DIR}/lib/cluster-hosts.sh"

BANK_ID="6275"
SESSION_ID=""
ROUND_ID=""
BET_AMOUNT="100"
WIN_AMOUNT="150"
RESERVE_COUNTER="1"
SETTLE_COUNTER="2"
GAME_ID="838"
MODE="real"
LANG="en"
TOKEN="test_user_6275"
TRANSPORT="host"
GS_BASE_URL="$(cluster_hosts_http_url GS_EXTERNAL_HOST GS_EXTERNAL_PORT 127.0.0.1 18081)"
PROTOCOL_BASE_URL="$(cluster_hosts_http_url PROTOCOL_ADAPTER_EXTERNAL_HOST PROTOCOL_ADAPTER_EXTERNAL_PORT 127.0.0.1 18078)"
GS_CONTAINER="refactor-gs-1"
PROTOCOL_CONTAINER="refactor-protocol-adapter-1"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --session-id SID          Optional (auto-detected if omitted)
  --bank-id ID              Default: ${BANK_ID}
  --token TOKEN             Default: ${TOKEN}
  --mode MODE               Default: ${MODE}
  --lang LANG               Default: ${LANG}
  --round-id ID             Default: autogenerated hex id
  --bet-amount AMOUNT       Default: ${BET_AMOUNT}
  --win-amount AMOUNT       Default: ${WIN_AMOUNT}
  --reserve-counter N       Default: ${RESERVE_COUNTER}
  --settle-counter N        Default: ${SETTLE_COUNTER}
  --game-id ID              Default: ${GAME_ID}
  --transport MODE          host|docker (default: ${TRANSPORT})
  --gs-base-url URL         Default: ${GS_BASE_URL}
  --protocol-base-url URL   Default: ${PROTOCOL_BASE_URL}
  --gs-container NAME       Default: ${GS_CONTAINER}
  --protocol-container NAME Default: ${PROTOCOL_CONTAINER}
  -h, --help                Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --session-id)
      SESSION_ID="$2"; shift 2 ;;
    --bank-id)
      BANK_ID="$2"; shift 2 ;;
    --token)
      TOKEN="$2"; shift 2 ;;
    --mode)
      MODE="$2"; shift 2 ;;
    --lang)
      LANG="$2"; shift 2 ;;
    --round-id)
      ROUND_ID="$2"; shift 2 ;;
    --bet-amount)
      BET_AMOUNT="$2"; shift 2 ;;
    --win-amount)
      WIN_AMOUNT="$2"; shift 2 ;;
    --reserve-counter)
      RESERVE_COUNTER="$2"; shift 2 ;;
    --settle-counter)
      SETTLE_COUNTER="$2"; shift 2 ;;
    --game-id)
      GAME_ID="$2"; shift 2 ;;
    --transport)
      TRANSPORT="$2"; shift 2 ;;
    --gs-base-url)
      GS_BASE_URL="$2"; shift 2 ;;
    --protocol-base-url)
      PROTOCOL_BASE_URL="$2"; shift 2 ;;
    --gs-container)
      GS_CONTAINER="$2"; shift 2 ;;
    --protocol-container)
      PROTOCOL_CONTAINER="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${ROUND_ID}" ]]; then
  ROUND_ID="$(printf '%x%08x' "$(date +%s)" "$RANDOM")"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd docker
require_cmd grep
require_cmd wc
require_cmd tr
require_cmd curl

extract_sid_from_file() {
  local file="$1"
  if [[ ! -f "${file}" ]]; then
    echo ""
    return 0
  fi
  local sid
  sid="$(grep -Eo 'SID=[^&"[:space:]]+' "${file}" | head -n1 | cut -d'=' -f2 || true)"
  if [[ -n "${sid}" ]]; then
    echo "${sid}"
    return 0
  fi
  echo ""
}

resolve_session_id() {
  local out_headers="$1"
  local out_body="$2"
  local launch_url
  if [[ "${TRANSPORT}" == "docker" ]]; then
    launch_url="http://127.0.0.1:8080/cwstartgamev2.do?bankId=${BANK_ID}&gameId=${GAME_ID}&mode=${MODE}&token=${TOKEN}&lang=${LANG}"
    if ! docker exec "${GS_CONTAINER}" sh -lc "curl -sS -D /tmp/phase4-protocol-wallet-launch.headers -o /tmp/phase4-protocol-wallet-launch.body '${launch_url}' >/dev/null"; then
      : > "${out_headers}"
      : > "${out_body}"
      echo ""
      return 0
    fi
    if ! docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase4-protocol-wallet-launch.headers" > "${out_headers}"; then
      : > "${out_headers}"
    fi
    if ! docker exec "${GS_CONTAINER}" sh -lc "cat /tmp/phase4-protocol-wallet-launch.body" > "${out_body}"; then
      : > "${out_body}"
    fi
  else
    launch_url="${GS_BASE_URL}/cwstartgamev2.do?bankId=${BANK_ID}&gameId=${GAME_ID}&mode=${MODE}&token=${TOKEN}&lang=${LANG}"
    if ! curl -sS -D "${out_headers}" -o "${out_body}" "${launch_url}" >/dev/null; then
      : > "${out_headers}"
      : > "${out_body}"
      echo ""
      return 0
    fi
  fi

  local sid
  sid="$(extract_sid_from_file "${out_headers}")"
  if [[ -z "${sid}" ]]; then
    sid="$(extract_sid_from_file "${out_body}")"
  fi
  echo "${sid}"
}

protocol_api_to_file() {
  local path="$1"
  local out_file="$2"
  if [[ "${TRANSPORT}" == "docker" ]]; then
    docker exec "${PROTOCOL_CONTAINER}" sh -lc "wget -qO- 'http://127.0.0.1:18078${path}'" > "${out_file}"
  else
    curl -sS "${PROTOCOL_BASE_URL}${path}" > "${out_file}"
  fi
}

count_protocol_events_from_file() {
  local file="$1"
  grep -o '"type":"PROTOCOL_REQUEST_EVALUATED"' "${file}" | wc -l | tr -d ' '
}

post_gs_internal() {
  local path="$1"
  local body="$2"
  local out_file="$3"
  local code_file="$4"
  if [[ "${TRANSPORT}" == "docker" ]]; then
    docker exec "${GS_CONTAINER}" sh -lc "curl -sS -X POST 'http://127.0.0.1:8080/gs-internal/newgames/v1${path}' -H 'Content-Type: application/json' -d '${body}' -o '${out_file}' -w '%{http_code}'" > "${code_file}"
    docker exec "${GS_CONTAINER}" sh -lc "cat '${out_file}'" > "${out_file}.host"
  else
    curl -sS -X POST "${GS_BASE_URL}/gs-internal/newgames/v1${path}" \
      -H 'Content-Type: application/json' \
      -d "${body}" \
      -o "${out_file}.host" \
      -w '%{http_code}' > "${code_file}"
  fi
}

extract_wallet_operation_id() {
  local json_file="$1"
  grep -o '"walletOperationId":"[^"]*"' "${json_file}" | head -n1 | cut -d':' -f2 | tr -d '"'
}

tmp_dir="$(mktemp -d)"
before_file="${tmp_dir}/before.json"
after_file="${tmp_dir}/after.json"
decision_file="${tmp_dir}/decision.json"
launch_headers_file="${tmp_dir}/launch.headers"
launch_body_file="${tmp_dir}/launch.body"
reserve_body_file="${tmp_dir}/reserve.body"
reserve_code_file="${tmp_dir}/reserve.code"
settle_body_file="${tmp_dir}/settle.body"
settle_code_file="${tmp_dir}/settle.code"
trap 'rm -rf "${tmp_dir}"' EXIT

if [[ -z "${SESSION_ID}" ]]; then
  SESSION_ID="$(resolve_session_id "${launch_headers_file}" "${launch_body_file}")"
fi
if [[ -z "${SESSION_ID}" ]]; then
  echo "FAIL: could not auto-resolve sessionId from startgame launch" >&2
  echo "Launch headers:" >&2
  cat "${launch_headers_file}" >&2 || true
  echo "Launch body snippet:" >&2
  sed -n '1,40p' "${launch_body_file}" >&2 || true
  exit 1
fi

protocol_api_to_file "/api/v1/protocol/events?limit=1000" "${before_file}"
before_count="$(count_protocol_events_from_file "${before_file}")"

protocol_api_to_file "/api/v1/protocol/routing/decision?bankId=${BANK_ID}" "${decision_file}"
if ! grep -q '"routeToProtocolAdapter":true' "${decision_file}"; then
  echo "FAIL: protocol-adapter canary route decision is not enabled for bank ${BANK_ID}" >&2
  echo "Decision payload: $(cat "${decision_file}")" >&2
  exit 2
fi

reserve_payload=$(cat <<JSON
{"sessionId":"${SESSION_ID}","roundId":"${ROUND_ID}","requestCounter":${RESERVE_COUNTER},"betAmount":${BET_AMOUNT},"gameId":${GAME_ID}}
JSON
)
post_gs_internal "/wallet/reserve" "${reserve_payload}" "/tmp/phase4-protocol-wallet-reserve.json" "${reserve_code_file}"
reserve_http_code="$(cat "${reserve_code_file}" | tr -d '\r\n')"
cp "/tmp/phase4-protocol-wallet-reserve.json.host" "${reserve_body_file}" 2>/dev/null || true

if [[ "${reserve_http_code}" != "200" ]]; then
  echo "FAIL: reserve returned HTTP ${reserve_http_code}" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 3
fi

wallet_operation_id="$(extract_wallet_operation_id "${reserve_body_file}")"
if [[ -z "${wallet_operation_id}" ]]; then
  echo "FAIL: walletOperationId missing in reserve response" >&2
  echo "Reserve body: $(cat "${reserve_body_file}" 2>/dev/null || true)" >&2
  exit 4
fi

settle_payload=$(cat <<JSON
{"sessionId":"${SESSION_ID}","roundId":"${ROUND_ID}","walletOperationId":"${wallet_operation_id}","requestCounter":${SETTLE_COUNTER},"winAmount":${WIN_AMOUNT},"gameId":${GAME_ID}}
JSON
)
post_gs_internal "/wallet/settle" "${settle_payload}" "/tmp/phase4-protocol-wallet-settle.json" "${settle_code_file}"
settle_http_code="$(cat "${settle_code_file}" | tr -d '\r\n')"
cp "/tmp/phase4-protocol-wallet-settle.json.host" "${settle_body_file}" 2>/dev/null || true

if [[ "${settle_http_code}" != "200" ]]; then
  echo "FAIL: settle returned HTTP ${settle_http_code}" >&2
  echo "Settle body: $(cat "${settle_body_file}" 2>/dev/null || true)" >&2
  exit 5
fi

sleep 1
protocol_api_to_file "/api/v1/protocol/events?limit=1000" "${after_file}"
after_count="$(count_protocol_events_from_file "${after_file}")"

echo "Protocol wallet shadow canary summary"
echo "  bankId: ${BANK_ID}"
echo "  sessionId: ${SESSION_ID}"
echo "  roundId: ${ROUND_ID}"
echo "  reserve_http: ${reserve_http_code}"
echo "  settle_http: ${settle_http_code}"
echo "  walletOperationId: ${wallet_operation_id}"
echo "  protocol_events_before: ${before_count}"
echo "  protocol_events_after: ${after_count}"

if (( after_count <= before_count )); then
  echo "FAIL: no protocol shadow events observed after reserve/settle" >&2
  exit 6
fi

echo "PASS: protocol-adapter wallet reserve/settle shadow observed (${before_count} -> ${after_count})."
