#!/usr/bin/env bash
set -euo pipefail

A_FILE=""
B_FILE=""
POLICY="strict"
OUT_FILE=""
MD_OUT_FILE=""
PRETTY="true"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Build a compact Phase 8 Wave 3 discrepancy comparison report from two JSON exports
generated by phase8-precision-wave3-discrepancy-export.sh. Applies a named threshold
policy and emits JSON (and optional Markdown).

Options:
  --a-file FILE        Baseline A discrepancy export JSON (required)
  --b-file FILE        Comparison B discrepancy export JSON (required)
  --policy NAME        strict|canary_gate|shadow_observe|demo_sample_pass (default: strict)
  --out-file FILE      Write JSON report output (default: stdout)
  --md-out-file FILE   Write Markdown report output (optional)
  --pretty BOOL        true|false pretty JSON (default: true)
  -h, --help           Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --a-file) A_FILE="$2"; shift 2 ;;
    --b-file) B_FILE="$2"; shift 2 ;;
    --policy) POLICY="$2"; shift 2 ;;
    --out-file) OUT_FILE="$2"; shift 2 ;;
    --md-out-file) MD_OUT_FILE="$2"; shift 2 ;;
    --pretty) PRETTY="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

[[ -n "${A_FILE}" ]] || { echo "--a-file is required" >&2; exit 1; }
[[ -n "${B_FILE}" ]] || { echo "--b-file is required" >&2; exit 1; }
[[ -f "${A_FILE}" ]] || { echo "Missing A file: ${A_FILE}" >&2; exit 1; }
[[ -f "${B_FILE}" ]] || { echo "Missing B file: ${B_FILE}" >&2; exit 1; }
[[ "${PRETTY}" == "true" || "${PRETTY}" == "false" ]] || { echo "--pretty must be true or false" >&2; exit 1; }

node - "${A_FILE}" "${B_FILE}" "${POLICY}" "${OUT_FILE}" "${MD_OUT_FILE}" "${PRETTY}" <<'NODE'
const fs = require('fs');

const [aFile, bFile, policyName, outFile, mdOutFile, prettyRaw] = process.argv.slice(2);
const pretty = prettyRaw === 'true';
const allowedPolicies = {
  strict: {
    label: 'Strict Gate',
    mismatchA: 0, mismatchB: 0, mismatchDelta: 0, snapshotDelta: 0, allowNewMetricsInB: false
  },
  canary_gate: {
    label: 'Canary Gate',
    mismatchA: 1, mismatchB: 1, mismatchDelta: 1, snapshotDelta: 25, allowNewMetricsInB: false
  },
  shadow_observe: {
    label: 'Shadow Observe',
    mismatchA: 5, mismatchB: 5, mismatchDelta: 5, snapshotDelta: 5000, allowNewMetricsInB: true
  },
  demo_sample_pass: {
    label: 'Demo Sample Pass',
    mismatchA: 1, mismatchB: 1, mismatchDelta: 1, snapshotDelta: 10, allowNewMetricsInB: true
  }
};

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function readJson(path) {
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  if (!data || typeof data !== 'object' || !data.metrics || typeof data.metrics !== 'object') {
    fail(`Invalid discrepancy export JSON: ${path}`);
  }
  return data;
}

function asNum(v, fallback = 0) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function hasMismatch(m) {
  if (!m) return false;
  return asNum(m.maxMismatchCount, 0) > 0 || asNum(m.mismatchEventsObserved, 0) > 0;
}

function countMismatchMetrics(model) {
  return Object.values(model.metrics || {}).filter(hasMismatch).length;
}

function buildMetricRows(aModel, bModel) {
  const keys = [...new Set([...Object.keys(aModel.metrics || {}), ...Object.keys(bModel.metrics || {})])];
  keys.sort((a, b) => String(a).localeCompare(String(b)));
  return keys.map((key) => {
    const a = aModel.metrics[key] || null;
    const b = bModel.metrics[key] || null;
    return {
      metric: key,
      aSnapshots: a ? asNum(a.snapshots, null) : null,
      aMaxMismatch: a ? asNum(a.maxMismatchCount, null) : null,
      bSnapshots: b ? asNum(b.snapshots, null) : null,
      bMaxMismatch: b ? asNum(b.maxMismatchCount, null) : null,
      deltaSnapshots: asNum(b && b.snapshots, 0) - asNum(a && a.snapshots, 0),
      deltaMismatch: asNum(b && b.maxMismatchCount, 0) - asNum(a && a.maxMismatchCount, 0),
      compareOnlyInB: !a && !!b
    };
  });
}

function rule(status, label, detail) { return { status, label, detail }; }

function buildRules(st) {
  const rules = [];
  rules.push(st.aMismatchMetrics <= st.thresholds.mismatchA
    ? rule('PASS', 'A mismatch metrics within threshold', `${st.aMismatchMetrics} <= ${st.thresholds.mismatchA}`)
    : rule('FAIL', 'A mismatch metrics exceed threshold', `${st.aMismatchMetrics} > ${st.thresholds.mismatchA}`));
  rules.push(st.bMismatchMetrics <= st.thresholds.mismatchB
    ? rule('PASS', 'B mismatch metrics within threshold', `${st.bMismatchMetrics} <= ${st.thresholds.mismatchB}`)
    : rule('FAIL', 'B mismatch metrics exceed threshold', `${st.bMismatchMetrics} > ${st.thresholds.mismatchB}`));
  rules.push(Math.abs(st.deltaMismatchMetrics) <= st.thresholds.mismatchDelta
    ? rule('PASS', 'Mismatch metric delta within threshold', `|${st.deltaMismatchMetrics}| <= ${st.thresholds.mismatchDelta}`)
    : rule('FAIL', 'Mismatch metric delta exceeds threshold', `|${st.deltaMismatchMetrics}| > ${st.thresholds.mismatchDelta}`));
  rules.push(Math.abs(st.deltaSnapshots) <= st.thresholds.snapshotDelta
    ? rule('PASS', 'Snapshot delta within threshold', `|${st.deltaSnapshots}| <= ${st.thresholds.snapshotDelta}`)
    : rule('FAIL', 'Snapshot delta exceeds threshold', `|${st.deltaSnapshots}| > ${st.thresholds.snapshotDelta}`));
  rules.push(st.thresholds.allowNewMetricsInB || st.newMetricsInB === 0
    ? rule('PASS', 'New metrics in B policy', st.thresholds.allowNewMetricsInB ? `allowed (${st.newMetricsInB} found)` : 'none found')
    : rule('FAIL', 'New metrics in B are not allowed', `${st.newMetricsInB} new metrics`));
  rules.push(st.maxMismatchDeltaAbs <= st.thresholds.mismatchDelta
    ? rule('PASS', 'Per-metric mismatch delta within threshold', `${st.maxMismatchDeltaAbs} <= ${st.thresholds.mismatchDelta}`)
    : rule('FAIL', 'Per-metric mismatch delta exceeds threshold', `${st.maxMismatchDeltaAbs} > ${st.thresholds.mismatchDelta}`));
  return rules;
}

const thresholds = allowedPolicies[policyName];
if (!thresholds) {
  fail(`Unknown policy: ${policyName}. Allowed: ${Object.keys(allowedPolicies).join(', ')}`);
}

const aModel = readJson(aFile);
const bModel = readJson(bFile);
const aMetricCount = Object.keys(aModel.metrics || {}).length;
const bMetricCount = Object.keys(bModel.metrics || {}).length;
const unionKeys = [...new Set([...Object.keys(aModel.metrics || {}), ...Object.keys(bModel.metrics || {})])];
let maxMismatchDeltaAbs = 0;
for (const k of unionKeys) {
  const a = aModel.metrics[k];
  const b = bModel.metrics[k];
  const delta = asNum(b && b.maxMismatchCount, 0) - asNum(a && a.maxMismatchCount, 0);
  maxMismatchDeltaAbs = Math.max(maxMismatchDeltaAbs, Math.abs(delta));
}

const state = {
  thresholds: { ...thresholds },
  aMismatchMetrics: countMismatchMetrics(aModel),
  bMismatchMetrics: countMismatchMetrics(bModel),
  deltaMismatchMetrics: countMismatchMetrics(bModel) - countMismatchMetrics(aModel),
  deltaSnapshots: asNum(bModel.totalSnapshotLines, 0) - asNum(aModel.totalSnapshotLines, 0),
  newMetricsInB: Object.keys(bModel.metrics || {}).filter((k) => !(k in (aModel.metrics || {}))).length,
  maxMismatchDeltaAbs,
  aMetricCount,
  bMetricCount,
  unionMetricCount: unionKeys.length
};

const rules = buildRules(state);
const passRules = rules.filter((r) => r.status === 'PASS').length;
const failRules = rules.filter((r) => r.status === 'FAIL').length;
const infoRules = rules.filter((r) => r.status === 'INFO').length;
const metricRows = buildMetricRows(aModel, bModel);

const report = {
  generatedAtUtc: new Date().toISOString(),
  type: 'phase8-wave3-discrepancy-compare-report',
  generator: 'phase8-precision-wave3-discrepancy-compare-export',
  sources: {
    baselineA: { file: aFile, sourceFiles: Array.isArray(aModel.sourceFiles) ? aModel.sourceFiles : [] },
    comparisonB: { file: bFile, sourceFiles: Array.isArray(bModel.sourceFiles) ? bModel.sourceFiles : [] }
  },
  thresholds: {
    ...state.thresholds,
    profile: policyName,
    profileLabel: thresholds.label
  },
  summary: {
    overall: failRules > 0 ? 'FAIL' : 'PASS',
    passRules,
    failRules,
    infoRules,
    aMismatchMetrics: state.aMismatchMetrics,
    bMismatchMetrics: state.bMismatchMetrics,
    deltaMismatchMetrics: state.deltaMismatchMetrics,
    aMetricCount: state.aMetricCount,
    bMetricCount: state.bMetricCount,
    unionMetricCount: state.unionMetricCount,
    newMetricsInB: state.newMetricsInB,
    deltaSnapshots: state.deltaSnapshots,
    maxMismatchDeltaAbs: state.maxMismatchDeltaAbs
  },
  rules,
  metrics: metricRows
};

const md = [];
md.push('# Phase 8 Wave 3 Discrepancy Comparison Report (CLI)');
md.push('');
md.push(`- generatedAtUtc: ${report.generatedAtUtc}`);
md.push(`- overall: ${report.summary.overall}`);
md.push(`- policy: ${report.thresholds.profile} (${report.thresholds.profileLabel})`);
md.push(`- aFile: ${aFile}`);
md.push(`- bFile: ${bFile}`);
md.push('');
md.push('## Thresholds');
md.push(`- mismatchA <= ${report.thresholds.mismatchA}`);
md.push(`- mismatchB <= ${report.thresholds.mismatchB}`);
md.push(`- mismatchDelta <= ${report.thresholds.mismatchDelta}`);
md.push(`- snapshotDelta <= ${report.thresholds.snapshotDelta}`);
md.push(`- allowNewMetricsInB: ${report.thresholds.allowNewMetricsInB}`);
md.push('');
md.push('## Summary');
md.push(`- passRules: ${report.summary.passRules}`);
md.push(`- failRules: ${report.summary.failRules}`);
md.push(`- aMismatchMetrics: ${report.summary.aMismatchMetrics}`);
md.push(`- bMismatchMetrics: ${report.summary.bMismatchMetrics}`);
md.push(`- deltaMismatchMetrics: ${report.summary.deltaMismatchMetrics}`);
md.push(`- newMetricsInB: ${report.summary.newMetricsInB}`);
md.push('');
md.push('## Rules');
for (const r of report.rules) md.push(`- [${r.status}] ${r.label} (${r.detail})`);
md.push('');
md.push('## Metric Deltas');
md.push('| metric | aMaxMismatch | bMaxMismatch | deltaMismatch | aSnapshots | bSnapshots | deltaSnapshots | compareOnlyInB |');
md.push('|---|---:|---:|---:|---:|---:|---:|---|');
for (const m of report.metrics) {
  md.push(`| ${m.metric} | ${m.aMaxMismatch ?? '-'} | ${m.bMaxMismatch ?? '-'} | ${m.deltaMismatch ?? '-'} | ${m.aSnapshots ?? '-'} | ${m.bSnapshots ?? '-'} | ${m.deltaSnapshots ?? '-'} | ${m.compareOnlyInB ? 'yes' : 'no'} |`);
}
const mdText = md.join('\n') + '\n';

const jsonText = JSON.stringify(report, null, pretty ? 2 : 0);
if (outFile) {
  fs.writeFileSync(outFile, jsonText + '\n', 'utf8');
  console.log(`out=${outFile}`);
}
if (mdOutFile) {
  fs.writeFileSync(mdOutFile, mdText, 'utf8');
  console.log(`md_out=${mdOutFile}`);
}
console.log(`summary overall=${report.summary.overall} policy=${policyName} metricCount=${report.metrics.length} failRules=${report.summary.failRules}`);
if (!outFile) process.stdout.write(jsonText + '\n');
NODE
