#!/usr/bin/env node
/**
 * config-gen — Generate GS Template Params from game.settings.json
 *
 * Usage (from repo root):
 *   npx tsx tools/config-gen/src/index.ts                           # generates for ALL games
 *   npx tsx tools/config-gen/src/index.ts --game premium-slot      # generates for one game
 *   npx tsx tools/config-gen/src/index.ts --check                   # CI: validates outputs are up-to-date
 *
 * Shortcuts via root package.json:
 *   pnpm config:gen
 *   pnpm config:check
 */

import fs from 'node:fs';
import path from 'node:path';

// ─── Types (mirrors @gamesv1/core-compliance GsRegistrationSchema) ─────────────────────────

interface MathModel {
    id: string;
    rtp: number;
    label?: string;
}

interface GsRegistration {
    mathModels: MathModel[];
    volatility: string;
    possibleMaxWinMultiplier: number;
    capWinMultiplier: number;
    releaseTime: number; // seconds
    isFrb: boolean;
    ocb: boolean;
}

interface GameSettings {
    gameId: string;
    gameName: string;
    version?: string;
    reels: { rows: number; cols: number };
    features: {
        freeSpins: boolean;
        buyFeature: boolean;
        autoplay: boolean;
    };
    gs?: GsRegistration;
}

// ─── Validation ──────────────────────────────────────────────────────────────

function validateGsBlock(gs: GsRegistration, gameName: string): string[] {
    const errors: string[] = [];

    // RTP values rounded to 2 decimals
    for (const model of gs.mathModels) {
        const rounded = Math.round(model.rtp * 100) / 100;
        if (model.rtp !== rounded) {
            errors.push(`[${gameName}] Math model "${model.id}" RTP ${model.rtp} is not rounded to 2 decimals (should be ${rounded}).`);
        }
    }

    // POSSIBLE_MAX_WINS must NOT equal CAP_WIN_MULTIPLIER
    if (gs.possibleMaxWinMultiplier === gs.capWinMultiplier) {
        errors.push(`[${gameName}] possibleMaxWinMultiplier (${gs.possibleMaxWinMultiplier}) must NOT equal capWinMultiplier (${gs.capWinMultiplier}).`);
    }

    // possibleMaxWin should be less than cap
    if (gs.possibleMaxWinMultiplier > gs.capWinMultiplier) {
        errors.push(`[${gameName}] possibleMaxWinMultiplier (${gs.possibleMaxWinMultiplier}) must be <= capWinMultiplier (${gs.capWinMultiplier}).`);
    }

    // Release time must be positive
    if (gs.releaseTime <= 0) {
        errors.push(`[${gameName}] releaseTime must be positive (got ${gs.releaseTime}).`);
    }

    // RTP array length must equal number of math models
    const rtpCount = gs.mathModels.length;
    if (rtpCount < 1) {
        errors.push(`[${gameName}] At least one math model is required.`);
    }

    return errors;
}

// ─── Generators ──────────────────────────────────────────────────────────────

function generateProperties(settings: GameSettings): string {
    const gs = settings.gs!;
    const lines: string[] = [
        `# Auto-generated by config-gen — DO NOT EDIT`,
        `# Source: game.settings.json for ${settings.gameName}`,
        `# Generated: ${new Date().toISOString().split('T')[0]}`,
        ``,
        `GAME_ID=${settings.gameId}`,
        `GAME_NAME=${settings.gameName}`,
        `GAME_VERSION=${settings.version || '1.0.0'}`,
        `REELS_ROWS=${settings.reels.rows}`,
        `REELS_COLS=${settings.reels.cols}`,
        ``,
        `# Math Models`,
        `MATH_MODEL_COUNT=${gs.mathModels.length}`,
    ];

    gs.mathModels.forEach((m, i) => {
        lines.push(`MATH_MODEL_${i}_ID=${m.id}`);
        lines.push(`MATH_MODEL_${i}_RTP=${m.rtp.toFixed(2)}`);
        if (m.label) lines.push(`MATH_MODEL_${i}_LABEL=${m.label}`);
    });

    const rtpArray = gs.mathModels.map(m => m.rtp.toFixed(2)).join(',');
    lines.push(`RTP_VALUES=${rtpArray}`);

    lines.push(``);
    lines.push(`# Win Limits`);
    lines.push(`VOLATILITY=${gs.volatility}`);
    lines.push(`POSSIBLE_MAX_WIN_MULTIPLIER=${gs.possibleMaxWinMultiplier}`);
    lines.push(`CAP_WIN_MULTIPLIER=${gs.capWinMultiplier}`);
    lines.push(`RELEASE_TIME=${gs.releaseTime}`);

    lines.push(``);
    lines.push(`# Flags`);
    lines.push(`IS_FRB=${gs.isFrb}`);
    lines.push(`OCB=${gs.ocb}`);
    lines.push(`FREE_SPINS=${settings.features.freeSpins}`);
    lines.push(`BUY_FEATURE=${settings.features.buyFeature}`);
    lines.push(`AUTOPLAY=${settings.features.autoplay}`);
    lines.push(``);

    return lines.join('\n');
}

function generateJson(settings: GameSettings): string {
    const gs = settings.gs!;
    const output = {
        gameId: settings.gameId,
        gameName: settings.gameName,
        version: settings.version || '1.0.0',
        reels: settings.reels,
        mathModels: gs.mathModels.map(m => ({
            id: m.id,
            rtp: parseFloat(m.rtp.toFixed(2)),
            label: m.label || m.id,
        })),
        rtpValues: gs.mathModels.map(m => parseFloat(m.rtp.toFixed(2))),
        volatility: gs.volatility,
        possibleMaxWinMultiplier: gs.possibleMaxWinMultiplier,
        capWinMultiplier: gs.capWinMultiplier,
        releaseTime: gs.releaseTime,
        isFrb: gs.isFrb,
        ocb: gs.ocb,
        features: {
            freeSpins: settings.features.freeSpins,
            buyFeature: settings.features.buyFeature,
            autoplay: settings.features.autoplay,
        },
    };
    return JSON.stringify(output, null, 2);
}

function generateRegistrationMd(settings: GameSettings): string {
    const gs = settings.gs!;
    const lines: string[] = [
        `# GS Registration — ${settings.gameName}`,
        ``,
        `> Auto-generated by \`config-gen\`. Do not edit manually.`,
        ``,
        `## Identity`,
        `| Field | Value |`,
        `|---|---|`,
        `| Game ID | \`${settings.gameId}\` |`,
        `| Game Name | ${settings.gameName} |`,
        `| Version | ${settings.version || '1.0.0'} |`,
        `| Grid | ${settings.reels.cols}×${settings.reels.rows} |`,
        ``,
        `## Math Models`,
        `| # | ID | RTP (%) | Label |`,
        `|---|---|---|---|`,
    ];

    gs.mathModels.forEach((m, i) => {
        lines.push(`| ${i + 1} | ${m.id} | ${m.rtp.toFixed(2)} | ${m.label || '—'} |`);
    });

    lines.push(``);
    lines.push(`## Win Limits`);
    lines.push(`| Field | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| Volatility | ${gs.volatility} |`);
    lines.push(`| Possible Max Win Multiplier | ${gs.possibleMaxWinMultiplier}× |`);
    lines.push(`| Cap Win Multiplier | ${gs.capWinMultiplier}× |`);
    lines.push(`| Release Time | ${gs.releaseTime}s |`);

    lines.push(``);
    lines.push(`## Flags`);
    lines.push(`| Flag | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| Is FRB | ${gs.isFrb ? '✅ Yes' : '❌ No'} |`);
    lines.push(`| OCB | ${gs.ocb ? '✅ Yes' : '❌ No'} |`);
    lines.push(`| Free Spins | ${settings.features.freeSpins ? '✅ Enabled' : '❌ Disabled'} |`);
    lines.push(`| Buy Feature | ${settings.features.buyFeature ? '✅ Enabled' : '❌ Disabled'} |`);
    lines.push(`| Autoplay | ${settings.features.autoplay ? '✅ Enabled' : '❌ Disabled'} |`);
    lines.push(``);

    return lines.join('\n');
}

// ─── File System Helpers ─────────────────────────────────────────────────────

function findGameDirs(gamesRoot: string, filterGame?: string): string[] {
    if (!fs.existsSync(gamesRoot)) return [];
    const entries = fs.readdirSync(gamesRoot, { withFileTypes: true });
    return entries
        .filter((e: fs.Dirent) => e.isDirectory())
        .filter((e: fs.Dirent) => !filterGame || e.name === filterGame)
        .map((e: fs.Dirent) => path.join(gamesRoot, e.name));
}

function findSettingsFile(gameDir: string): string | null {
    const settingsPath = path.join(gameDir, 'game.settings.json');
    if (fs.existsSync(settingsPath)) return settingsPath;
    return null;
}

// ─── Main Logic ──────────────────────────────────────────────────────────────

function processGame(gameDir: string, checkOnly: boolean): { errors: string[]; generated: boolean } {
    const gameName = path.basename(gameDir);
    const settingsPath = findSettingsFile(gameDir);

    if (!settingsPath) {
        return { errors: [], generated: false };
    }

    const raw = fs.readFileSync(settingsPath, 'utf-8');
    let settings: GameSettings;
    try {
        settings = JSON.parse(raw);
    } catch {
        return { errors: [`[${gameName}] Invalid JSON in game.settings.json`], generated: false };
    }

    if (!settings.gs) {
        // No gs block — game not configured for GS registration yet, skip
        return { errors: [], generated: false };
    }

    // Validate
    const validationErrors = validateGsBlock(settings.gs, gameName);
    if (validationErrors.length > 0) {
        return { errors: validationErrors, generated: false };
    }

    const gsDir = path.join(gameDir, 'gs');

    if (checkOnly) {
        // Verify outputs exist and match
        const errors: string[] = [];
        const propsPath = path.join(gsDir, 'template-params.properties');
        const jsonPath = path.join(gsDir, 'template-params.json');
        const mdPath = path.join(gsDir, 'registration.md');

        if (!fs.existsSync(propsPath)) {
            errors.push(`[${gameName}] Missing gs/template-params.properties — run: npm run config:gen`);
        }
        if (!fs.existsSync(jsonPath)) {
            errors.push(`[${gameName}] Missing gs/template-params.json — run: npm run config:gen`);
        }
        if (!fs.existsSync(mdPath)) {
            errors.push(`[${gameName}] Missing gs/registration.md — run: npm run config:gen`);
        }

        // Check if JSON output is stale
        if (fs.existsSync(jsonPath)) {
            const expected = generateJson(settings);
            const actual = fs.readFileSync(jsonPath, 'utf-8');
            try {
                if (JSON.stringify(JSON.parse(expected)) !== JSON.stringify(JSON.parse(actual))) {
                    errors.push(`[${gameName}] gs/template-params.json is stale — run: npm run config:gen`);
                }
            } catch {
                errors.push(`[${gameName}] gs/template-params.json is malformed — run: npm run config:gen`);
            }
        }

        return { errors, generated: false };
    }

    // Generate
    if (!fs.existsSync(gsDir)) {
        fs.mkdirSync(gsDir, { recursive: true });
    }

    const propsContent = generateProperties(settings);
    const jsonContent = generateJson(settings);
    const mdContent = generateRegistrationMd(settings);

    fs.writeFileSync(path.join(gsDir, 'template-params.properties'), propsContent);
    fs.writeFileSync(path.join(gsDir, 'template-params.json'), jsonContent);
    fs.writeFileSync(path.join(gsDir, 'registration.md'), mdContent);

    console.log(`  ✅ ${gameName}: generated gs/template-params.{properties,json} + registration.md`);
    return { errors: [], generated: true };
}

// ─── CLI (zero-dependency arg parsing) ───────────────────────────────────────

function parseArgs(argv: string[]): { game?: string; check: boolean } {
    let game: string | undefined;
    let check = false;

    for (let i = 2; i < argv.length; i++) {
        if (argv[i] === '--game' && argv[i + 1]) {
            game = argv[++i];
        } else if (argv[i] === '--check') {
            check = true;
        }
    }

    return { game, check };
}

const { game, check } = parseArgs(process.argv);
const projectRoot = path.resolve(process.cwd());
const gamesRoot = path.join(projectRoot, 'games');

if (check) {
    console.log('🔍 Config Check: validating generated outputs...\n');
} else {
    console.log('🎰 Config Gen: generating GS template params...\n');
}

const gameDirs = findGameDirs(gamesRoot, game);

if (gameDirs.length === 0) {
    console.log('  No game directories found.');
    process.exit(0);
}

let allErrors: string[] = [];
let totalGenerated = 0;

for (const dir of gameDirs) {
    const result = processGame(dir, check);
    allErrors = allErrors.concat(result.errors);
    if (result.generated) totalGenerated++;
}

if (allErrors.length > 0) {
    console.error('\n❌ Errors found:\n');
    allErrors.forEach(e => console.error(`  • ${e}`));
    process.exit(1);
}

if (check) {
    console.log('✅ All generated outputs are up-to-date.');
} else {
    console.log(`\n✅ Done. Generated for ${totalGenerated} game(s).`);
}


